spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/luckymoney?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database: mysql
server:
  port: 8081
  servlet:
    context-path: /app

limit:
  minMoney: 2
  maxMoney: 99
  description: 最少要发${limit.minMoney}元,最多${limit.maxMoney}元